import { createFileRoute } from "@tanstack/react-router";
import { BookingLink, ConsultationBand, PageIntro, SectionHeading } from "@/components/site-chrome";
import { values } from "@/lib/site-content";

export const Route = createFileRoute("/about")({ head: () => ({ meta: [
  { title: "About Us | Psychologists Hub Islamabad" }, { name: "description", content: "Get to know Psychologists Hub, a female-led psychology practice in Islamabad dedicated to compassionate, confidential mental health support." },
  { property: "og:title", content: "About Psychologists Hub" }, { property: "og:description", content: "Compassionate care, thoughtful listening, and a commitment to mental wellbeing in Islamabad." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" },
] }), component: About });

function About() { return <main><PageIntro label="About us / 01" title="Care with purpose. Space to grow." description="A practice built on the belief that everyone deserves to be heard, understood, and supported."/>
  <section className="max-w-[1500px] mx-auto px-5 md:px-10 xl:px-14 py-20 md:py-32 grid md:grid-cols-[.7fr_1.3fr] gap-10 md:gap-24"><p className="eyebrow text-sage-deep pt-3">Our mission</p><div><h2 className="display text-5xl md:text-7xl">Mental wellbeing belongs to <em className="font-normal text-sage-deep">everyone.</em></h2><p className="mt-9 text-muted-foreground leading-8 max-w-2xl">Psychologists Hub is a female-led practice dedicated to making mental health care accessible and compassionate. Through tailored therapy, education, workshops, and community engagement, we work to make conversations about mental health more open—and support more people in living well.</p><p className="mt-5 text-muted-foreground leading-8 max-w-2xl">From the first conversation to continued care, we approach every person with respect, integrity, and a deep commitment to privacy.</p></div></section>
  <section className="bg-surface"><div className="max-w-[1500px] mx-auto px-5 md:px-10 xl:px-14 py-20 md:py-28"><SectionHeading label="Our values" title={<>The principles behind <em className="font-normal">our practice.</em></>}/><div className="grid md:grid-cols-3 gap-10 mt-16">{values.map((v,i)=><div key={v.title} className="number-rule pt-6"><span className="eyebrow text-sage-deep">0{i+1}</span><v.icon className="mt-12 text-sage-deep" size={30} strokeWidth={1.2}/><h3 className="font-display text-3xl mt-5">{v.title}</h3><p className="mt-4 text-muted-foreground text-sm leading-7">{v.description}</p></div>)}</div></div></section>
  <section className="max-w-[1500px] mx-auto px-5 md:px-10 xl:px-14 py-20 md:py-28 grid md:grid-cols-2 gap-12"><div><p className="eyebrow text-sage-deep mb-7">Your journey with us</p><h2 className="display text-5xl md:text-7xl">One step<br/>at a time.</h2></div><div className="space-y-0">{[["01","An initial conversation","We listen to your story, understand what brings you here, and discuss what support could look like."],["02","Understanding your needs","Where appropriate, assessment helps us build a clearer picture together."],["03","A path made for you","Therapeutic sessions are shaped around your goals, preferences, and pace."]].map(([n,t,d])=><div key={n} className="border-t border-border py-6 grid grid-cols-[3rem_1fr] gap-4"><span className="text-sage-deep text-xs">{n}</span><div><h3 className="font-display text-3xl">{t}</h3><p className="mt-2 text-sm text-muted-foreground leading-7">{d}</p></div></div>)}<BookingLink>Begin with a conversation</BookingLink></div></section><ConsultationBand/></main>; }