import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowLeft, ArrowUpRight, CalendarDays, Phone, ShieldCheck } from "lucide-react";
import { Button } from "@/components/ui/button";
import { bookingUrl, PageIntro, phone } from "@/components/site-chrome";

export const Route = createFileRoute("/book-appointment")({ head: () => ({ meta: [
  { title: "Book an Appointment | Psychologists Hub Islamabad" }, { name: "description", content: "Schedule a confidential therapy appointment with Psychologists Hub in Islamabad or online using our booking calendar, or call the clinic directly." },
  { property: "og:title", content: "Book an Appointment | Psychologists Hub" }, { property: "og:description", content: "Take the first step and schedule a conversation with Psychologists Hub." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" },
] }), component: BookAppointment });

function BookAppointment() { return <main><PageIntro label="Book an appointment / 07" title="Your first step starts here." description="Whenever you’re ready, choose a time that works for you. We look forward to meeting you."/>
  <section className="max-w-[1500px] mx-auto px-5 md:px-10 xl:px-14 py-20 md:py-28 grid lg:grid-cols-[1.1fr_.9fr] gap-16 lg:gap-28"><div><p className="eyebrow text-sage-deep mb-7">Make an appointment</p><h2 className="display text-5xl md:text-7xl max-w-2xl">Let’s find a time to <em className="font-normal text-sage-deep">talk.</em></h2><p className="mt-8 text-muted-foreground leading-8 max-w-lg">Choose a convenient time through our appointment calendar. You’ll leave this site to complete your booking securely with the clinic’s scheduling service.</p><Button asChild variant="editorial" size="spacious" className="mt-10"><a href={bookingUrl} target="_blank" rel="noopener noreferrer">Open booking calendar <ArrowUpRight /></a></Button><p className="mt-5 text-xs text-muted-foreground">Opens in a new tab.</p></div>
    <div className="bg-surface p-7 md:p-12 self-start"><CalendarDays size={32} strokeWidth={1.2} className="text-sage-deep"/><h3 className="font-display text-4xl mt-10">Prefer to speak first?</h3><p className="text-sm leading-7 text-muted-foreground mt-5">You’re welcome to call us with any questions before booking.</p><a href="tel:+923461555542" className="mt-8 inline-flex items-center gap-3 font-display text-3xl hover:underline"><Phone size={19} strokeWidth={1.3}/>{phone}</a><div className="mt-10 pt-6 border-t border-border flex gap-3 items-start text-sm leading-6 text-muted-foreground"><ShieldCheck size={20} className="text-sage-deep shrink-0" strokeWidth={1.3}/><p>Your wellbeing and privacy are always treated with care.</p></div></div>
  </section><div className="max-w-[1500px] mx-auto px-5 md:px-10 xl:px-14 pb-20"><Link to="/" className="inline-flex gap-2 items-center text-sm border-b border-primary pb-2"><ArrowLeft size={16}/> Back to home</Link></div></main>; }