import { createFileRoute } from "@tanstack/react-router";
import { ArrowUpRight, Mail, MapPin, Phone } from "lucide-react";
import { BookingLink, email, phone, PageIntro } from "@/components/site-chrome";

export const Route = createFileRoute("/contact")({ head: () => ({ meta: [
  { title: "Contact Psychologists Hub | Islamabad Psychology Clinic" }, { name: "description", content: "Get in touch with Psychologists Hub in Islamabad. Find our Soan Garden and Naval Anchorage clinic locations, phone number and email." },
  { property: "og:title", content: "Contact Psychologists Hub" }, { property: "og:description", content: "Reach out to Psychologists Hub in Islamabad. We’re here to listen." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" },
] }), component: Contact });

function Contact() { return <main><PageIntro label="Contact / 06" title="We’re here when you’re ready." description="Have a question or ready to take the first step? Reach out in the way that feels easiest for you."/>
  <section className="max-w-[1500px] mx-auto px-5 md:px-10 xl:px-14 py-20 md:py-28 grid lg:grid-cols-[.9fr_1.1fr] gap-16 lg:gap-28"><div><p className="eyebrow text-sage-deep mb-7">Get in touch</p><h2 className="display text-5xl md:text-7xl">Let’s start a <em className="font-normal text-sage-deep">conversation.</em></h2><p className="mt-8 text-muted-foreground leading-8 max-w-md">You don’t need to have the right words. Whether you’re looking for support or simply want to learn more, we’re happy to hear from you.</p><div className="mt-9"><BookingLink>Book an appointment</BookingLink></div></div>
    <div><div className="border-t border-border py-7 flex gap-6"><Phone className="text-sage-deep shrink-0 mt-1" size={22} strokeWidth={1.3}/><div><p className="eyebrow text-sage-deep mb-3">Call us</p><a href="tel:+923461555542" className="font-display text-3xl hover:underline">{phone}</a></div></div><div className="border-t border-border py-7 flex gap-6"><Mail className="text-sage-deep shrink-0 mt-1" size={22} strokeWidth={1.3}/><div><p className="eyebrow text-sage-deep mb-3">Email us</p><a href={`mailto:${email}`} className="font-display text-2xl sm:text-3xl break-all hover:underline">{email}</a></div></div><div className="border-t border-border py-7 flex gap-6"><MapPin className="text-sage-deep shrink-0 mt-1" size={22} strokeWidth={1.3}/><div><p className="eyebrow text-sage-deep mb-3">Visit us</p><p className="font-display text-2xl sm:text-3xl">Soan Garden, Islamabad</p><p className="mt-3 text-sm leading-7 text-muted-foreground">Office # M-1, Mezzanine Floor, Paris Business Center, Soan Garden, Islamabad.</p><a href="https://www.google.com/maps/search/?api=1&query=Paris+Business+Center+Soan+Garden+Islamabad" target="_blank" rel="noopener noreferrer" className="mt-4 inline-flex gap-2 items-center text-sm border-b border-primary pb-1">Get directions <ArrowUpRight size={16}/></a></div></div><div className="border-t border-border py-7 flex gap-6"><MapPin className="text-sage-deep shrink-0 mt-1" size={22} strokeWidth={1.3}/><div><p className="eyebrow text-sage-deep mb-3">Also available at</p><p className="font-display text-2xl sm:text-3xl">Naval Anchorage, Islamabad</p><p className="mt-3 text-sm leading-7 text-muted-foreground">Islamabad Health Services, Naval Anchorage, Islamabad.</p></div></div></div></section></main>; }