import { createFileRoute } from "@tanstack/react-router";
import { Monitor, ShieldCheck, MapPin } from "lucide-react";
import { BookingLink, ConsultationBand, PageIntro, SectionHeading } from "@/components/site-chrome";

export const Route = createFileRoute("/online-therapy")({ head: () => ({ meta: [
  { title: "Online Therapy in Pakistan | Psychologists Hub" }, { name: "description", content: "Access compassionate, confidential online therapy from Psychologists Hub. Connect with psychological support from wherever you feel comfortable." },
  { property: "og:title", content: "Online Therapy | Psychologists Hub" }, { property: "og:description", content: "Compassionate support, wherever you are. Explore online therapy with Psychologists Hub." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" },
] }), component: OnlineTherapy });

function OnlineTherapy() { return <main><PageIntro label="Online therapy / 03" title="Good care has no distance." description="A meaningful conversation can happen wherever you are. Make room for your wellbeing from a place that feels right to you."/>
  <section className="max-w-[1500px] mx-auto px-5 md:px-10 xl:px-14 py-20 md:py-28"><SectionHeading label="Care beyond the clinic" title={<>Your space. <em className="font-normal text-sage-deep">Your pace.</em></>} aside="Online sessions bring confidential, professional psychological support into your everyday life."/><div className="mt-16 grid md:grid-cols-3 gap-10">{[{icon:MapPin,title:"Wherever you are",text:"Connect from a private, comfortable place that works for you."},{icon:ShieldCheck,title:"A confidential space",text:"The same thoughtful, respectful approach to care—without the commute."},{icon:Monitor,title:"Real connection",text:"Meet with a psychologist online and have the conversations that matter."}].map((v,i)=><div key={v.title} className="number-rule pt-6"><span className="eyebrow text-sage-deep">0{i+1}</span><v.icon size={32} strokeWidth={1.2} className="text-sage-deep mt-14"/><h3 className="font-display text-3xl mt-6">{v.title}</h3><p className="text-sm leading-7 text-muted-foreground mt-4">{v.text}</p></div>)}</div></section>
  <section className="bg-surface"><div className="max-w-[1500px] mx-auto px-5 md:px-10 xl:px-14 py-20 md:py-28 grid md:grid-cols-2 gap-16 items-center"><div><p className="eyebrow text-sage-deep mb-7">Getting started</p><h2 className="display text-5xl md:text-7xl">The first step can be <em className="font-normal">simple.</em></h2></div><div><p className="text-muted-foreground leading-8 mb-8">Choose a time through our booking page and we’ll take it from there. Whether you’re navigating anxiety, low mood, relationships, or a difficult season, this is a place to start talking.</p><BookingLink>Book an online session</BookingLink></div></div></section><ConsultationBand/></main>; }