import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowUpRight } from "lucide-react";
import { BookingLink, ConsultationBand, PageIntro, SectionHeading } from "@/components/site-chrome";
import { services } from "@/lib/site-content";

export const Route = createFileRoute("/services")({ head: () => ({ meta: [
  { title: "Therapy & Psychology Services | Psychologists Hub" }, { name: "description", content: "Explore therapy for anxiety, depression, relationships and trauma, plus psychological assessments and workplace wellbeing in Islamabad and online." },
  { property: "og:title", content: "Therapy & Psychology Services | Psychologists Hub" }, { property: "og:description", content: "Individualised mental health care, psychological assessments, and workplace wellbeing." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" },
] }), component: Services });

function Services() { return <main><PageIntro label="Our services / 02" title="Support that meets you where you are." description="No two people are the same. Our care is shaped around your experiences, needs, and hopes for what comes next."/>
  <section className="max-w-[1500px] mx-auto px-5 md:px-10 xl:px-14 py-20 md:py-28"><SectionHeading label="What we offer" title={<>Room for every <em className="font-normal text-sage-deep">part of life.</em></>} aside="Explore a range of confidential, considered services in person and online."/><div className="mt-16 border-t border-border">{services.map((item,i)=><div key={item.title} className="grid md:grid-cols-[.4fr_1fr_1fr_.2fr] gap-5 items-start py-8 md:py-10 border-b border-border"><span className="eyebrow text-sage-deep pt-2">0{i+1}</span><h3 className="font-display text-3xl md:text-4xl">{item.title}</h3><p className="text-sm leading-7 text-muted-foreground max-w-md">{item.description}</p><item.icon size={26} strokeWidth={1.2} className="text-sage-deep hidden md:block justify-self-end"/></div>)}</div></section>
  <section className="bg-surface"><div className="max-w-[1500px] mx-auto px-5 md:px-10 xl:px-14 py-20 md:py-24 grid md:grid-cols-2 gap-16"><div><p className="eyebrow text-sage-deep mb-7">Psychological assessments</p><h2 className="display text-5xl md:text-6xl">A clearer picture can make all the difference.</h2></div><div className="flex flex-col justify-end"><p className="text-muted-foreground leading-8">We also offer personality assessments and intelligence testing tailored to individual needs, with a detailed report to help make sense of the results. These assessments are separate from psychotherapy sessions.</p><div className="mt-8"><BookingLink>Ask about an assessment</BookingLink></div></div></div></section>
  <section className="max-w-[1500px] mx-auto px-5 md:px-10 xl:px-14 py-16 flex flex-col md:flex-row justify-between gap-6"><p className="font-display text-3xl md:text-4xl">Prefer to meet from home?</p><Link to="/online-therapy" className="inline-flex items-center gap-2 text-sm font-semibold border-b border-primary pb-2 self-start">Explore online therapy <ArrowUpRight size={17}/></Link></section><ConsultationBand/></main>; }